export const ACTION_TYPE = {
  FETCH_LOCATION_LIST_PROCESSING: 'FETCH_LOCATION_LIST_PROCESSING',
  FETCH_LOCATION_LIST_SUCCESS: 'FETCH_LOCATION_LIST_SUCCESS',
  FETCH_LOCATION_LIST_FAILURE: 'FETCH_LOCATION_LIST_FAILURE',
  RESET_LOCATION_LIST: 'FETCH_LOCATION_LIST',

  FETCH_CURRENT_LOCATION_SELECTED_PROCESSING: 'FETCH_CURRENT_LOCATION_SELECTED_PROCESSING',
  FETCH_CURRENT_LOCATION_SELECTED_SUCCESS: 'FETCH_CURRENT_LOCATION_SELECTED_SUCCESS',
  FETCH_CURRENT_LOCATION_SELECTED_FAILURE: 'FETCH_CURRENT_LOCATION_SELECTED_FAILURE',
  RESET_CURRENT_LOCATION_SELECTED: 'RESET_CURRENT_LOCATION_SELECTED',

  UPDATE_SEARCHING_STATUS: 'UPDATE_SEARCHING_STATUS',
  SET_CURRENT_LOCATION_ID: 'SET_CURRENT_LOCATION_ID',
}